### ISSUE TITLE
Doesn't seem to work with tags?

### ISSUE THREAD

**Issue by scalp42** [mwrock/kitchen-nodes#21]
Using the following `kitchen.yml`:

``` yaml

---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 2048

verifier:
  name: inspec

provisioner:
  name: nodes
  data_bags_path: <%= ENV['HOME'] + '/chef/data_bags' %>
  environments_path: <%= ENV['HOME'] + '/chef/environments' %>
  roles_path: <%= ENV['HOME'] + '/chef/roles' %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] %>
  chef_omnibus_url: https://www.chef.io/chef/install.sh
  client_rb:
    environment: kitchen

platforms:
  - name: ubuntu-14.04
    driver:
      image: phusion/baseimage
      box: "ubuntu-14.04-chef-#{ENV['CHEF_VERSION']}"
      network:
        - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]
        - ["forwarded_port", {guest: 5050, host: 5050, auto_correct: true}]
        - ["forwarded_port", {guest: 5051, host: 5051, auto_correct: true}]
        - ["private_network", { type: "dhcp" }]

suites:
- name: master
  driver:
    pre_create_command: docker-compose up -d zk || true
  run_list:
  - recipe[vagrant-ohai]
  - recipe[mesos::master]
  attributes:
    boot2docker: <%= `docker-machine ip docker` %>
- name: slave
  run_list:
  - recipe[vagrant-ohai]
  - recipe[mesos::slave]
  attributes:
    boot2docker: <%= `docker-machine ip docker` %>
```

Scenario: the `mesos::master` recipe registers a tag and the `mesos::slave` looks for the tag.

Unfortunately, trying to converge multiple times, the two nodes don't appear to find each other.

I also checked within the `/tmp/kitchen/nodes` folder and it appears to look good:

```
root@master-ubuntu-1404:/tmp/kitchen/nodes# ll
total 156
drwxr-xr-x 2 vagrant vagrant   4096 Mar 26 04:44 ./
drwxrwxr-x 9 vagrant vagrant   4096 Mar 26 04:44 ../
-rw-r--r-- 1 vagrant vagrant 145318 Mar 26 04:45 master-ubuntu-1404.json
-rw-r--r-- 1 vagrant vagrant    382 Mar 26 04:44 slave-ubuntu-1404.json
root@master-ubuntu-1404:/tmp/kitchen/nodes# cat slave-ubuntu-1404.json | jq '.automatic.ipaddress'
"172.28.128.14"

root@slave-ubuntu-1404:/tmp/kitchen/nodes# ll
total 156
drwxr-xr-x 2 vagrant vagrant   4096 Mar 26 04:37 ./
drwxrwxr-x 9 vagrant vagrant   4096 Mar 26 04:44 ../
-rw-r--r-- 1 vagrant vagrant    386 Mar 26 04:44 master-ubuntu-1404.json
-rw-r--r-- 1 vagrant vagrant 145291 Mar 26 04:46 slave-ubuntu-1404.json
root@slave-ubuntu-1404:/tmp/kitchen/nodes# cat master-ubuntu-1404.json | jq '.automatic.ipaddress'
"172.28.128.13"
```

The master recipe:

``` ruby
  if tagged? "mesos.master.vagrantvbox.#{node.chef_environment}"
    log %|Already tagged Mesos MASTER node (Vagrant VirtualBox) #{node['ipaddress']} as available|
  else
    log %|Tagging Mesos MASTER node (Vagrant VirtualBox) #{node['ipaddress']} as available|
    tag "mesos.master.vagrantvbox.#{node.chef_environment}"
  end
```

The master log:

```
       Recipe: mesos::master
         * service[mesos-master] action enable (up to date)
         * service[mesos-master] action start (up to date)
         * log[Tagging Mesos MASTER node (Vagrant VirtualBox) 172.28.128.13 as available] action write
```

The slave recipe simply does a search for the master tag and defaults to itself if nothing found:

```
       [2016-03-26T04:44:56+00:00] WARN: mesos => Could not find any node matching "tags:mesos.master.vagrantvbox.kitchen", assuming a single Mesos MASTER node.
```

Any chance I'd be missing something on the test-kitchen or chef-zero side?

I've noticed it's missing the tag attributes so maybe it's not supported:

``` json
root@master-ubuntu-1404:/tmp/kitchen/nodes# cat slave-ubuntu-1404.json
{
  "id": "slave-ubuntu-1404",
  "chef_environment": "kitchen",
  "automatic": {
    "ipaddress": "172.28.128.14",
    "platform": "ubuntu",
    "fqdn": "slave-ubuntu-1404",
    "recipes": [
      "vagrant-ohai",
      "mesos::slave"
    ]
  },
  "normal": {
    "boot2docker": "192.168.99.100"
  },
  "run_list": [
    "recipe[vagrant-ohai]",
    "recipe[mesos::slave]"
  ]
```

``` json
root@slave-ubuntu-1404:/tmp/kitchen/nodes# cat master-ubuntu-1404.json
{
  "id": "master-ubuntu-1404",
  "chef_environment": "kitchen",
  "automatic": {
    "ipaddress": "172.28.128.13",
    "platform": "ubuntu",
    "fqdn": "master-ubuntu-1404",
    "recipes": [
      "vagrant-ohai",
      "mesos::master"
    ]
  },
  "normal": {
    "boot2docker": "192.168.99.100"
  },
  "run_list": [
    "recipe[vagrant-ohai]",
    "recipe[mesos::master]"
  ]
```

Thanks a lot in advance!

**Comment by scalp42** [comment]
Poking more the tags are indeed present on the master node data:

```
root@master-ubuntu-1404:/tmp/kitchen/nodes# cat master-ubuntu-1404.json
{
  "name": "master-ubuntu-1404",
  "chef_environment": "kitchen",
  "override": {
    "nodejs": {
      "install_method": "package",
      "packages": [
        "gz-nodejs"
      ]
    }
  },
  "normal": {
    "boot2docker": "192.168.99.100",
    "tags": [
      "mesos.master.vagrantvbox.kitchen"
    ],
```

I'm starting assume maybe it's an issue on chef-zero side with tags search?

**Comment by mwrock** [comment]
Yeah I tend to think it's a chef zero issue if you see the tags in the node json on the test instance.

**Comment by scalp42** [comment]
Never too late but looking at the code, only the kitchen attributes get dumped to json:

```ruby
normal: config[:attributes]
```

Only the kitchen attributes in `kitchen.yml` will appear so as a workaround, simply add the tags in kitchen:

```yaml
  - name: client
    run_list:
      - recipe[xxx-vagrant]
      - recipe[xxx-sensu]
      - recipe[xxx-sensu-kitchen]
    attributes:
      tags:
        - xxx-sensu.server.kitchen
```

Not perfect but close enough.
