### ISSUE TITLE
can't load 'nodes' provisioner from load path

### ISSUE THREAD

**Issue by smartb-pair** [mwrock/kitchen-nodes#29]
We may be missing something easy, but we keep seeing this error when trying to use the 'nodes' plugin:
```
$ bundle exec kitchen converge postgres
-----> Starting Kitchen (v1.13.2)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'nodes' provisioner from the load path. Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Our sanitized `.kitchen.yml` looks like this:
```
---
driver:
  name: joyent

transport:
  name: rsync

driver_config:
  joyent_version: '~7.0'
  joyent_username: smartb
  joyent_keyfile: <redacted>
  joyent_keyname: <redacted>
  joyent_url: https://eu-ams-1.api.joyent.com
  joyent_image_id: 643d5524-7eba-4a72-8fca-8dbb84d8d35d # ubuntu-certified-14.04
  joyent_flavor_id: k4-highcpu-kvm-3.75G
  username: ubuntu

provisioner:
  name: nodes
  require_chef_omnibus: 12.13.37

platforms:
  - name: ubuntu-14.04

suites:
  - name: pgbouncer
    run_list:
      - recipe[postgres::pgbouncer]

  - name: postgres-primary
    run_list:
      - recipe[postgres::primary]

  - name: postgres-replica
    run_list:
      - recipe[postgres::replica]
```

cc: @arochaf @bixu
