### ISSUE TITLE
Windows FQDN constructed from internal hostname rather than Openstack instance name

### ISSUE THREAD

**Issue by cbrit** [mwrock/kitchen-nodes#38]
Hello;
Kitchen-nodes has been working great for CentOS instances, but I'm having an issue where my Windows 2012 R2 instance will populate the nodes json with the internal windows hostname (like WIN-123BFKDS812 for example) rather than the "kitchen" name for the node defined by the Openstack instance name. 

kitchen.yml info

```
driver:
  name: openstack

provisioner:
  name: nodes

platforms:
  - name: centos-6.7
  - name: windows-2012r2-standard-gui

...

 - name: default
    includes:
      - windows-2012r2
    run_list:
      - recipe[cookbook::recipe]
```

Here is a normal (working) centos nodes json "automatic" section

```
  "automatic": {
    "ipaddress": "10.1.1.1",
    "platform": "centos",
    "fqdn": "username-tk-default-cookbook-env.domain.com",
    "recipes": [
      "cookbook::recipe"
    ]
  }
```

and my incorrect windows nodes json "automatic" section

```
  "automatic": {
    "ipaddress": "10.1.1.2",
    "platform": "windows",
    "fqdn": "WIN-1OQLPP07BAL.domain.com",
    "recipes": [
      "cookbook::recipe"
    ]
  }
```
I need to to populate the "fqdn" attribute with something similar to the centos nodes. I saw in the Changelog there were similar issues addressed; is this some setting that I am missing?

Changed some of the info in code for private reasons.

Thanks.

EDIT: Removed the error message after realizing it is generated by a recipe, not kitchen.
